import type { Metadata } from "next";
import { Inter, IBM_Plex_Serif } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";

import { Header } from "@/components/header/header";
const sans = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const serif = IBM_Plex_Serif({
  weight: ["700", "400"],
  style: ["italic", "normal"],
  display: "swap",
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        " bg-background antialiased",
        sans.variable,
        serif.variable
      )}
    >
      <body className="relative">
        <Header />
        <main className="py-[72px]">{children}</main>
      </body>
    </html>
  );
}
